"""empty message

Revision ID: 0efbf011deb0
Revises: 35ee0d6723ef
Create Date: 2023-03-18 15:02:08.168525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efbf011deb0'
down_revision = '35ee0d6723ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('About_me', sa.Text(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('About_me')

    # ### end Alembic commands ###
