"""empty message

Revision ID: 299feceab0d4
Revises: 68e06b879fc3
Create Date: 2023-03-14 21:34:58.043874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299feceab0d4'
down_revision = '68e06b879fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['poster_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###
