"""empty message

Revision ID: 7dad9ad8e101
Revises: b63884679720
Create Date: 2023-03-22 21:37:19.903098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dad9ad8e101'
down_revision = 'b63884679720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Photoer_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('photos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['Photoer_id'], ['id'])
        batch_op.drop_column('Photo_author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Photo_author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('photos_ibfk_1', 'user', ['Photo_author_id'], ['id'])
        batch_op.drop_column('Photoer_id')

    # ### end Alembic commands ###
