"""empty message

Revision ID: 86f2a510628e
Revises: 12391fb15071
Create Date: 2023-03-22 21:53:10.503590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86f2a510628e'
down_revision = '12391fb15071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photoer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('photos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['photoer_id'], ['id'])
        batch_op.drop_column('Photoer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Photoer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('photos_ibfk_1', 'user', ['Photoer_id'], ['id'])
        batch_op.drop_column('photoer_id')

    # ### end Alembic commands ###
