"""empty message

Revision ID: 97387d3db68b
Revises: 2b48b84a55f4
Create Date: 2023-03-20 21:33:46.766749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97387d3db68b'
down_revision = '2b48b84a55f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('Image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Image_path', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
