"""empty message

Revision ID: a449ab3ab640
Revises: 97387d3db68b
Create Date: 2023-03-22 19:44:05.826049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a449ab3ab640'
down_revision = '97387d3db68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Photoer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['Photoer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Photoer_id')

    # ### end Alembic commands ###
