"""empty message

Revision ID: d5ed7e1d8ac2
Revises: 
Create Date: 2023-03-06 21:15:17.093410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5ed7e1d8ac2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.create_unique_constraint(None, ['password'])
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
